
all :
	rm -f METAFeyn*
	feynmf diagrams.tex
	feynmf diagrams.tex
	dvips diagrams.dvi
	ps2eps -f diagrams.ps
	epstopdf diagrams.eps

	feynmf diagram_qq_w.tex
	feynmf diagram_qq_w.tex
	dvips diagram_qq_w.dvi
	ps2eps -f diagram_qq_w.ps
	epstopdf diagram_qq_w.eps

	feynmf diagram_qg_w.tex
	feynmf diagram_qg_w.tex
	dvips diagram_qg_w.dvi
	ps2eps -f diagram_qg_w.ps
	epstopdf diagram_qg_w.eps

	feynmf diagram_gg_w.tex
	feynmf diagram_gg_w.tex
	dvips diagram_gg_w.dvi
	ps2eps -f diagram_gg_w.ps
	epstopdf diagram_gg_w.eps

	feynmf diagram_qq_wgg_1.tex
	feynmf diagram_qq_wgg_1.tex
	dvips diagram_qq_wgg_1.dvi
	ps2eps -f diagram_qq_wgg_1.ps
	epstopdf diagram_qq_wgg_1.eps

	feynmf diagram_qq_wgg_2.tex
	feynmf diagram_qq_wgg_2.tex
	dvips diagram_qq_wgg_2.dvi
	ps2eps -f diagram_qq_wgg_2.ps
	epstopdf diagram_qq_wgg_2.eps

	feynmf diagram_qq_wgg_3.tex
	feynmf diagram_qq_wgg_3.tex
	dvips diagram_qq_wgg_3.dvi
	ps2eps -f diagram_qq_wgg_3.ps
	epstopdf diagram_qq_wgg_3.eps

	feynmf diagram_qq_wgg_4.tex
	feynmf diagram_qq_wgg_4.tex
	dvips diagram_qq_wgg_4.dvi
	ps2eps -f diagram_qq_wgg_4.ps
	epstopdf diagram_qq_wgg_4.eps

	feynmf diagram_qq_wgg_5.tex
	feynmf diagram_qq_wgg_5.tex
	dvips diagram_qq_wgg_5.dvi
	ps2eps -f diagram_qq_wgg_5.ps
	epstopdf diagram_qq_wgg_5.eps

	feynmf diagram_qq_wgg_6.tex
	feynmf diagram_qq_wgg_6.tex
	dvips diagram_qq_wgg_6.dvi
	ps2eps -f diagram_qq_wgg_6.ps
	epstopdf diagram_qq_wgg_6.eps

	feynmf diagram_qq_wgg_7.tex
	feynmf diagram_qq_wgg_7.tex
	dvips diagram_qq_wgg_7.dvi
	ps2eps -f diagram_qq_wgg_7.ps
	epstopdf diagram_qq_wgg_7.eps
